// Standalone Frontend Commerce Mock Data Store
export const initialMockData = {
  user: {
    _id: 'usr_001',
    name: 'Kiaan Sharma',
    email: 'admin@kiaan.com',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    phone: '+91 98765 43210',
    status: 'Active',
    permissions: ['all'],
  },

  categories: [
    { _id: 'cat_001', name: "Women's Ethnic", slug: 'womens-ethnic', itemCount: 2842, image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80', description: 'Kurtas, Banarasi sarees, flared lehengas and sharara suits' },
    { _id: 'cat_002', name: "Women's Western", slug: 'womens-western', itemCount: 1948, image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80', description: 'Maxi dresses, crop tops, co-ords, trousers and skirts' },
    { _id: 'cat_003', name: "Men's Casuals", slug: 'mens-casuals', itemCount: 1560, image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80', description: 'Oversized streetwear tees, cargo pants, hoodies & shorts' },
    { _id: 'cat_004', name: "Men's Formals", slug: 'mens-formals', itemCount: 1248, image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=400&q=80', description: 'Linen shirts, Italian fit blazers, suits & tailored trousers' },
    { _id: 'cat_005', name: "Kids Collection", slug: 'kids-collection', itemCount: 980, image: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=400&q=80', description: 'Organic cotton co-ords, festive lehengas and party suits' },
    { _id: 'cat_006', name: "Festive & Winter", slug: 'festive-winter', itemCount: 840, image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=400&q=80', description: 'Silk Nehru sets, embroidered shawls, velvet kurtas & coats' },
  ],

  brands: [
    { _id: 'br_001', name: 'Aura Studio', logo: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=200&q=80', productsCount: 142 },
    { _id: 'br_002', name: 'UrbanThread', logo: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?auto=format&fit=crop&w=200&q=80', productsCount: 128 },
    { _id: 'br_003', name: 'Kaira Ethnic', logo: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=200&q=80', productsCount: 215 },
    { _id: 'br_004', name: 'Royal Heritage', logo: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=200&q=80', productsCount: 94 },
  ],

  products: [
    {
      _id: 'prd_001',
      name: "Embroidered Anarkali Kurta Set",
      category: "Women's Ethnic",
      brand: "Kaira Ethnic",
      sku: "KUR-W-9021",
      price: 2499,
      compareAtPrice: 4999,
      costPrice: 950,
      stock: 148,
      lowStockThreshold: 20,
      rating: 4.8,
      reviewsCount: 342,
      salesCount: 1840,
      revenue: 4598160,
      status: "Published",
      badge: "Bestseller",
      description: "Premium rayon fabric with intricate Zari needlework, flared hemline, matching dupatta and palazzo.",
      images: [
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80",
      ],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      variants: [
        { size: 'S', color: 'Burgundy', stock: 35, sku: 'KUR-W-9021-S' },
        { size: 'M', color: 'Burgundy', stock: 45, sku: 'KUR-W-9021-M' },
        { size: 'L', color: 'Burgundy', stock: 40, sku: 'KUR-W-9021-L' },
        { size: 'XL', color: 'Burgundy', stock: 28, sku: 'KUR-W-9021-XL' },
      ],
      flashSale: true,
      soldPercent: 88,
    },
    {
      _id: 'prd_002',
      name: "Urban Oversized Heavyweight 240 GSM Tee",
      category: "Men's Casuals",
      brand: "UrbanThread",
      sku: "TEE-M-4011",
      price: 799,
      compareAtPrice: 1499,
      costPrice: 280,
      stock: 310,
      lowStockThreshold: 40,
      rating: 4.6,
      reviewsCount: 512,
      salesCount: 2450,
      revenue: 1957550,
      status: "Published",
      badge: "Hot Streetwear",
      description: "240 GSM pure combed cotton drop-shoulder streetwear t-shirt with ribbed neck and anti-fade dye.",
      images: [
        "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80",
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      variants: [
        { size: 'M', color: 'Charcoal Grey', stock: 120, sku: 'TEE-M-4011-M-CG' },
        { size: 'L', color: 'Charcoal Grey', stock: 110, sku: 'TEE-M-4011-L-CG' },
      ],
      flashSale: true,
      soldPercent: 74,
    },
    {
      _id: 'prd_003',
      name: "Royal Banarasi Silk Zari Woven Saree",
      category: "Women's Ethnic",
      brand: "Kaira Ethnic",
      sku: "SAR-W-7721",
      price: 3899,
      compareAtPrice: 7999,
      costPrice: 1450,
      stock: 52,
      lowStockThreshold: 10,
      rating: 4.9,
      reviewsCount: 178,
      salesCount: 620,
      revenue: 2417380,
      status: "Published",
      badge: "Festive Silk",
      description: "Authentic Varanasi woven silk saree with rich golden zari borders and intricate floral pallu motifs.",
      images: [
        "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80"
      ],
      sizes: ['Free Size'],
      variants: [
        { size: 'Free Size', color: 'Royal Emerald', stock: 26, sku: 'SAR-W-7721-EM' },
        { size: 'Free Size', color: 'Crimson Red', stock: 26, sku: 'SAR-W-7721-RED' },
      ],
      flashSale: false,
      soldPercent: 68,
    },
    {
      _id: 'prd_004',
      name: "Tailored Italian Fit Wool Blend Blazer",
      category: "Men's Formals",
      brand: "UrbanThread",
      sku: "BLZ-M-5502",
      price: 4999,
      compareAtPrice: 8999,
      costPrice: 1900,
      stock: 36,
      lowStockThreshold: 8,
      rating: 4.7,
      reviewsCount: 112,
      salesCount: 430,
      revenue: 2149570,
      status: "Published",
      badge: "Gentleman Fit",
      description: "Structured slim fit notch lapel single-breasted blazer with premium silk lining and horn buttons.",
      images: [
        "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80"
      ],
      sizes: ['38R', '40R', '42R', '44R'],
      variants: [
        { size: '38R', color: 'Midnight Navy', stock: 12, sku: 'BLZ-38' },
        { size: '40R', color: 'Midnight Navy', stock: 14, sku: 'BLZ-40' },
        { size: '42R', color: 'Midnight Navy', stock: 10, sku: 'BLZ-42' },
      ],
      flashSale: false,
      soldPercent: 58,
    },
    {
      _id: 'prd_005',
      name: "Floral Tiered Bohemian Chiffon Maxi Dress",
      category: "Women's Western",
      brand: "Aura Studio",
      sku: "DRS-W-3200",
      price: 1899,
      compareAtPrice: 3499,
      costPrice: 650,
      stock: 82,
      lowStockThreshold: 15,
      rating: 4.5,
      reviewsCount: 220,
      salesCount: 910,
      revenue: 1728090,
      status: "Published",
      badge: "Summer Pick",
      description: "Flowy chiffon maxi dress with smocked waistline, ruffled hemline and breathable inner cotton lining.",
      images: [
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80"
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      variants: [
        { size: 'M', color: 'Sage Floral', stock: 35, sku: 'DRS-M' },
        { size: 'L', color: 'Sage Floral', stock: 47, sku: 'DRS-L' },
      ],
      flashSale: false,
      soldPercent: 55,
    },
    {
      _id: 'prd_006',
      name: "Minimalist Solid French Linen Shirt",
      category: "Men's Formals",
      brand: "UrbanThread",
      sku: "SHR-M-1120",
      price: 1399,
      compareAtPrice: 2499,
      costPrice: 480,
      stock: 94,
      lowStockThreshold: 20,
      rating: 4.6,
      reviewsCount: 140,
      salesCount: 680,
      revenue: 951320,
      status: "Published",
      badge: "100% Linen",
      description: "Pure French flax linen breathable tailored shirt with mother-of-pearl buttons and mandarin collar.",
      images: [
        "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80"
      ],
      sizes: ['38', '40', '42', '44'],
      variants: [
        { size: '40', color: 'Ivory White', stock: 34, sku: 'SHR-40-WHT' },
        { size: '42', color: 'Ivory White', stock: 60, sku: 'SHR-42-WHT' },
      ],
      flashSale: false,
      soldPercent: 48,
    },
    {
      _id: 'prd_007',
      name: "Kids Dino Graphic Organic Cotton Co-ord Set",
      category: "Kids Collection",
      brand: "UrbanThread",
      sku: "KID-B-3310",
      price: 899,
      compareAtPrice: 1599,
      costPrice: 320,
      stock: 140,
      lowStockThreshold: 25,
      rating: 4.8,
      reviewsCount: 230,
      salesCount: 1120,
      revenue: 1006880,
      status: "Published",
      badge: "Kids Fav",
      description: "Ultra-soft 100% GOTS certified organic breathable cotton t-shirt and matching stretch cargo shorts.",
      images: [
        "https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?auto=format&fit=crop&w=600&q=80"
      ],
      sizes: ['3-4 Y', '5-6 Y', '7-8 Y', '9-10 Y'],
      variants: [
        { size: '3-4 Y', color: 'Sage Green', stock: 35, sku: 'KID-3Y' },
        { size: '5-6 Y', color: 'Sage Green', stock: 45, sku: 'KID-5Y' },
        { size: '7-8 Y', color: 'Sage Green', stock: 60, sku: 'KID-7Y' },
      ],
      flashSale: true,
      soldPercent: 78,
    },
    {
      _id: 'prd_008',
      name: "Girls Festive Foil Printed Flared Lehenga Choli",
      category: "Kids Collection",
      brand: "Kaira Ethnic",
      sku: "KID-G-8812",
      price: 1699,
      compareAtPrice: 3299,
      costPrice: 580,
      stock: 65,
      lowStockThreshold: 15,
      rating: 4.9,
      reviewsCount: 164,
      salesCount: 780,
      revenue: 1325220,
      status: "Published",
      badge: "Festive Ready",
      description: "Lightweight art silk flared lehenga with hand-embroidered mirrorwork blouse and soft net dupatta.",
      images: [
        "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=600&q=80"
      ],
      sizes: ['4-5 Y', '6-7 Y', '8-9 Y'],
      variants: [
        { size: '4-5 Y', color: 'Blush Pink', stock: 20, sku: 'LHG-4Y' },
        { size: '6-7 Y', color: 'Blush Pink', stock: 25, sku: 'LHG-6Y' },
        { size: '8-9 Y', color: 'Blush Pink', stock: 20, sku: 'LHG-8Y' },
      ],
      flashSale: false,
      soldPercent: 62,
    },
    {
      _id: 'prd_009',
      name: "Ribbed Knit Crop Top & Wide Leg Trousers Set",
      category: "Women's Western",
      brand: "Aura Studio",
      sku: "SET-W-4410",
      price: 1599,
      compareAtPrice: 2999,
      costPrice: 520,
      stock: 75,
      lowStockThreshold: 12,
      rating: 4.7,
      reviewsCount: 195,
      salesCount: 820,
      revenue: 1311180,
      status: "Published",
      badge: "Trending Co-ord",
      description: "Premium stretchable ribbed cotton knit top paired with high-waist palazzo style wide trousers.",
      images: [
        "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      variants: [
        { size: 'S', color: 'Lavender', stock: 25, sku: 'SET-S' },
        { size: 'M', color: 'Lavender', stock: 30, sku: 'SET-M' },
        { size: 'L', color: 'Lavender', stock: 20, sku: 'SET-L' },
      ],
      flashSale: true,
      soldPercent: 80,
    },
    {
      _id: 'prd_010',
      name: "Tapered Stretch Cargo Streetwear Pants",
      category: "Men's Casuals",
      brand: "UrbanThread",
      sku: "CRG-M-6620",
      price: 1299,
      compareAtPrice: 2499,
      costPrice: 420,
      stock: 110,
      lowStockThreshold: 20,
      rating: 4.7,
      reviewsCount: 280,
      salesCount: 1350,
      revenue: 1753650,
      status: "Published",
      badge: "Cargo Fit",
      description: "Heavy twill stretch cotton with 6 utility cargo pockets, elastic drawstring waist and ankle cuffs.",
      images: [
        "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=600&q=80",
      ],
      sizes: ['30', '32', '34', '36'],
      variants: [
        { size: '32', color: 'Olive Green', stock: 45, sku: 'CRG-32-OLV' },
        { size: '34', color: 'Olive Green', stock: 40, sku: 'CRG-34-OLV' },
      ],
      flashSale: false,
      soldPercent: 70,
    },
    {
      _id: 'prd_011',
      name: "Royal Heritage Silk Nehru Jacket & Kurta Set",
      category: "Festive & Winter",
      brand: "Royal Heritage",
      sku: "NHR-M-8801",
      price: 3499,
      compareAtPrice: 6999,
      costPrice: 1200,
      stock: 44,
      lowStockThreshold: 10,
      rating: 4.9,
      reviewsCount: 134,
      salesCount: 520,
      revenue: 1819480,
      status: "Published",
      badge: "Wedding Festive",
      description: "Jacquard woven floral motif Nehru sleeveless jacket over raw silk kurta and churidar pajama.",
      images: [
        "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80",
      ],
      sizes: ['38', '40', '42', '44'],
      variants: [
        { size: '40', color: 'Gold Mustard', stock: 20, sku: 'NHR-40' },
        { size: '42', color: 'Gold Mustard', stock: 24, sku: 'NHR-42' },
      ],
      flashSale: true,
      soldPercent: 85,
    },
    {
      _id: 'prd_012',
      name: "Hand-Block Printed Chanderi Cotton Kurti",
      category: "Women's Ethnic",
      brand: "Kaira Ethnic",
      sku: "KRT-W-2210",
      price: 1199,
      compareAtPrice: 2299,
      costPrice: 380,
      stock: 130,
      lowStockThreshold: 20,
      rating: 4.8,
      reviewsCount: 260,
      salesCount: 1420,
      revenue: 1702580,
      status: "Published",
      badge: "Hand Block",
      description: "Traditional Bagru indigo block print on featherlight Chanderi cotton with wooden button placket.",
      images: [
        "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80",
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      variants: [
        { size: 'S', color: 'Indigo Blue', stock: 30, sku: 'KRT-S' },
        { size: 'M', color: 'Indigo Blue', stock: 45, sku: 'KRT-M' },
        { size: 'L', color: 'Indigo Blue', stock: 55, sku: 'KRT-L' },
      ],
      flashSale: false,
      soldPercent: 65,
    }
  ],

  orders: [
    {
      _id: 'ord_82942',
      orderNumber: 'ORD-82942',
      customer: {
        id: 'cst_001',
        name: 'Rahul Sharma',
        email: 'rahul.sharma@gmail.com',
        phone: '+91 98234 11223',
        avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
      },
      items: [
        {
          productId: 'prd_001',
          name: 'Embroidered Anarkali Kurta Set',
          image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=150&q=80',
          size: 'M',
          color: 'Burgundy',
          quantity: 1,
          unitPrice: 2499,
          total: 2499,
        },
        {
          productId: 'prd_003',
          name: 'Zenith Velocity Air Cushion Sneakers',
          image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=150&q=80',
          size: 'UK 8',
          color: 'Ruby Crimson',
          quantity: 1,
          unitPrice: 2499,
          total: 2499,
        }
      ],
      subtotal: 4998,
      discount: 500,
      couponCode: 'WELCOME10',
      shippingFee: 0,
      tax: 224.9,
      totalAmount: 4722.9,
      paymentStatus: 'Paid',
      paymentMethod: 'UPI (Google Pay)',
      orderStatus: 'Delivered',
      shippingAddress: {
        street: 'Flat 402, Lotus Residency, Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560038',
        country: 'India',
      },
      trackingNumber: 'DEL-8829104',
      courierPartner: 'Delhivery Express',
      timeline: [
        { status: 'Order Placed', time: '18 May, 10:24 AM', completed: true },
        { status: 'Payment Confirmed', time: '18 May, 10:25 AM', completed: true },
        { status: 'Packed & Dispatched', time: '18 May, 04:30 PM', completed: true },
        { status: 'Shipped (In Transit)', time: '19 May, 09:15 AM', completed: true },
        { status: 'Delivered', time: '21 May, 02:40 PM', completed: true },
      ],
      createdAt: '2026-05-18T10:24:00Z',
    },
    {
      _id: 'ord_82943',
      orderNumber: 'ORD-82943',
      customer: {
        id: 'cst_002',
        name: 'Ananya Deshmukh',
        email: 'ananya.d@yahoo.com',
        phone: '+91 97123 99887',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
      },
      items: [
        {
          productId: 'prd_005',
          name: 'Handcrafted Italian Leather Tote Bag',
          image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=150&q=80',
          size: 'Standard',
          color: 'Cognac Tan',
          quantity: 1,
          unitPrice: 3299,
          total: 3299,
        }
      ],
      subtotal: 3299,
      discount: 0,
      shippingFee: 0,
      tax: 164.95,
      totalAmount: 3463.95,
      paymentStatus: 'Paid',
      paymentMethod: 'Credit Card (HDFC)',
      orderStatus: 'Shipped',
      shippingAddress: {
        street: 'Villa 14, Silver Oak Estate, Baner',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411045',
        country: 'India',
      },
      trackingNumber: 'BLU-3091823',
      courierPartner: 'BlueDart Air',
      timeline: [
        { status: 'Order Placed', time: '22 May, 02:15 PM', completed: true },
        { status: 'Payment Confirmed', time: '22 May, 02:16 PM', completed: true },
        { status: 'Packed & Dispatched', time: '23 May, 11:00 AM', completed: true },
        { status: 'Shipped (In Transit)', time: '23 May, 06:45 PM', completed: true },
        { status: 'Delivered', time: 'Expected 25 May', completed: false },
      ],
      createdAt: '2026-05-22T14:15:00Z',
    },
    {
      _id: 'ord_82944',
      orderNumber: 'ORD-82944',
      customer: {
        id: 'cst_003',
        name: 'Vikramaditya Rao',
        email: 'vikram.rao@outlook.com',
        phone: '+91 99011 22334',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      },
      items: [
        {
          productId: 'prd_002',
          name: 'Urban Oversized Heavyweight Tee',
          image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=150&q=80',
          size: 'L',
          color: 'Charcoal Grey',
          quantity: 2,
          unitPrice: 799,
          total: 1598,
        }
      ],
      subtotal: 1598,
      discount: 100,
      couponCode: 'SUMMER100',
      shippingFee: 50,
      tax: 79.9,
      totalAmount: 1627.9,
      paymentStatus: 'Paid',
      paymentMethod: 'UPI (PhonePe)',
      orderStatus: 'Processing',
      shippingAddress: {
        street: '12B Jubilee Hills, Road No 36',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500033',
        country: 'India',
      },
      trackingNumber: 'Pending',
      courierPartner: 'Shiprocket Surface',
      timeline: [
        { status: 'Order Placed', time: '24 May, 09:30 AM', completed: true },
        { status: 'Payment Confirmed', time: '24 May, 09:31 AM', completed: true },
        { status: 'Processing & Quality Check', time: '24 May, 11:20 AM', completed: true },
        { status: 'Shipped (In Transit)', time: 'Pending', completed: false },
        { status: 'Delivered', time: 'Pending', completed: false },
      ],
      createdAt: '2026-05-24T09:30:00Z',
    },
    {
      _id: 'ord_82945',
      orderNumber: 'ORD-82945',
      customer: {
        id: 'cst_004',
        name: 'Sneha Kapadia',
        email: 'sneha.k@gmail.com',
        phone: '+91 98450 12345',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      },
      items: [
        {
          productId: 'prd_004',
          name: 'Glow Radiance Vitamin C Saffron Serum',
          image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=150&q=80',
          size: '30ml',
          color: 'Gold Dropper',
          quantity: 2,
          unitPrice: 899,
          total: 1798,
        }
      ],
      subtotal: 1798,
      discount: 0,
      shippingFee: 0,
      tax: 89.9,
      totalAmount: 1887.9,
      paymentStatus: 'Pending (COD)',
      paymentMethod: 'Cash on Delivery',
      orderStatus: 'Confirmed',
      shippingAddress: {
        street: '78 Sector 15, Vashi',
        city: 'Navi Mumbai',
        state: 'Maharashtra',
        pincode: '400703',
        country: 'India',
      },
      trackingNumber: 'Pending',
      courierPartner: 'Delhivery Surface',
      timeline: [
        { status: 'Order Placed', time: '24 May, 11:45 AM', completed: true },
        { status: 'COD Verified by OTP', time: '24 May, 11:46 AM', completed: true },
      ],
      createdAt: '2026-05-24T11:45:00Z',
    }
  ],

  customers: [
    {
      _id: 'cst_001',
      name: 'Rahul Sharma',
      email: 'rahul.sharma@gmail.com',
      phone: '+91 98234 11223',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
      segment: 'VIP',
      totalOrders: 14,
      totalSpent: 48920,
      averageOrderValue: 3494,
      lastPurchase: '2026-05-18T10:24:00Z',
      status: 'Active',
      city: 'Bengaluru',
    },
    {
      _id: 'cst_002',
      name: 'Ananya Deshmukh',
      email: 'ananya.d@yahoo.com',
      phone: '+91 97123 99887',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
      segment: 'VIP',
      totalOrders: 8,
      totalSpent: 27400,
      averageOrderValue: 3425,
      lastPurchase: '2026-05-22T14:15:00Z',
      status: 'Active',
      city: 'Pune',
    },
    {
      _id: 'cst_003',
      name: 'Vikramaditya Rao',
      email: 'vikram.rao@outlook.com',
      phone: '+91 99011 22334',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      segment: 'Returning',
      totalOrders: 4,
      totalSpent: 9800,
      averageOrderValue: 2450,
      lastPurchase: '2026-05-24T09:30:00Z',
      status: 'Active',
      city: 'Hyderabad',
    },
    {
      _id: 'cst_004',
      name: 'Sneha Kapadia',
      email: 'sneha.k@gmail.com',
      phone: '+91 98450 12345',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      segment: 'New',
      totalOrders: 1,
      totalSpent: 1887.9,
      averageOrderValue: 1887.9,
      lastPurchase: '2026-05-24T11:45:00Z',
      status: 'Active',
      city: 'Navi Mumbai',
    }
  ],

  campaigns: [
    {
      _id: 'cmp_001',
      name: 'Mega Summer Sale 🎉',
      description: 'Up to 60% Off on Fashion & Lifestyle',
      banner: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
      runTime: '12 May - 25 May',
      productsCount: 842,
      revenue: 124890,
      orders: 312,
      roas: 4.8,
      conversion: '4.2%',
      status: 'Active',
    },
    {
      _id: 'cmp_002',
      name: 'Ethnic Grand Utsav',
      description: 'Exclusive Bridal & Festive Handcrafted Wear',
      banner: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
      runTime: '01 Jun - 10 Jun',
      productsCount: 420,
      revenue: 0,
      orders: 0,
      roas: 0,
      conversion: '0%',
      status: 'Scheduled',
    }
  ],

  coupons: [
    {
      _id: 'cpn_001',
      code: 'SUMMER60',
      discountType: 'percentage',
      discountValue: 60,
      minOrderAmount: 1999,
      usageLimit: 1000,
      usedCount: 418,
      expiryDate: '2026-05-30',
      status: 'Active',
      description: 'Get 60% off up to ₹1,200 on orders above ₹1,999',
    },
    {
      _id: 'cpn_002',
      code: 'WELCOME10',
      discountType: 'percentage',
      discountValue: 10,
      minOrderAmount: 999,
      usageLimit: 5000,
      usedCount: 1280,
      expiryDate: '2026-12-31',
      status: 'Active',
      description: 'Extra 10% off for first-time buyers',
    },
    {
      _id: 'cpn_003',
      code: 'VIPFASHION',
      discountType: 'fixed',
      discountValue: 500,
      minOrderAmount: 2999,
      usageLimit: 200,
      usedCount: 89,
      expiryDate: '2026-06-15',
      status: 'Active',
      description: 'Flat ₹500 discount for Gold and VIP tier members',
    }
  ],

  affiliates: [
    {
      _id: 'aff_001',
      name: 'Kavya & Trends (Instagram)',
      partnerCode: 'KAVYA20',
      category: 'Fashion Influencer',
      clicks: 14200,
      orders: 432,
      revenueGenerated: 648000,
      commissionRate: 10,
      payoutBalance: 64800,
    },
    {
      _id: 'aff_002',
      name: 'Desi Streetwear Club',
      partnerCode: 'DESISTREET',
      category: 'YouTube Reviewer',
      clicks: 8900,
      orders: 280,
      revenueGenerated: 392000,
      commissionRate: 8,
      payoutBalance: 31360,
    }
  ],

  reviews: [
    {
      _id: 'rev_001',
      productName: 'Embroidered Anarkali Kurta Set',
      customerName: 'Meera Rajput',
      rating: 5,
      title: 'Outstanding fabric and royal feel!',
      comment: 'The zari embroidery is truly exquisite and looks far more luxurious in real life. Fitting is impeccable.',
      date: '2026-05-20',
      verifiedPurchase: true,
      status: 'Approved',
    },
    {
      _id: 'rev_002',
      productName: 'Zenith Velocity Air Cushion Sneakers',
      customerName: 'Arjun Nambiar',
      rating: 5,
      title: 'Super soft bounce, best gym shoes',
      comment: 'I run 5km daily, the air sole absorbs shock like high-end marathon shoes. Highly recommended!',
      date: '2026-05-19',
      verifiedPurchase: true,
      status: 'Approved',
    }
  ],

  analytics: {
    overview: {
      totalRevenue: 284920,
      revenueGrowth: '+24.8%',
      totalOrders: 128,
      ordersGrowth: '+18.2%',
      totalCustomers: 892,
      customersGrowth: '+21.6%',
      productsSold: 1248,
      productsSoldGrowth: '+17.3%',
      conversionRate: 3.24,
      conversionGrowth: '+8.6%',
      storeHealthScore: 85,
    },
    salesChart: [
      { day: 'Mon', revenue: 32400, orders: 18, profit: 12900 },
      { day: 'Tue', revenue: 38200, orders: 22, profit: 15200 },
      { day: 'Wed', revenue: 45600, orders: 26, profit: 18300 },
      { day: 'Thu', revenue: 41200, orders: 20, profit: 16100 },
      { day: 'Fri', revenue: 52800, orders: 28, profit: 21400 },
      { day: 'Sat', revenue: 64900, orders: 34, profit: 26500 },
      { day: 'Sun', revenue: 71200, orders: 38, profit: 29800 },
    ],
    aiInsights: [
      {
        id: 'ai_001',
        type: 'Growth Spike',
        title: 'Sales surged 24.8% this week!',
        description: 'The Mega Summer Sale campaign drove a 42% lift in mobile conversions across Women Ethnic and Footwear.',
        impact: 'High Impact',
        actionText: 'Scale Campaign Budget',
      },
      {
        id: 'ai_002',
        type: 'Inventory Alert',
        title: '18 products are running low on stock',
        description: 'Classic Chronograph Watch and Italian Leather Tote Bags will stock out in 48 hours at current velocity.',
        impact: 'Action Required',
        actionText: 'Auto-Reorder from Suppliers',
      }
    ]
  },

  storeSettings: {
    storeName: "Kiaan Luxe Emporium",
    storeTagline: "India's Premier Fashion & Lifestyle Destination",
    supportEmail: "support@kiaantechnology.com",
    supportPhone: "+91 80000 12345",
    address: "Tower 4, Embassy Tech Village, Outer Ring Road, Bengaluru 560103",
    currency: "INR (₹)",
    gstin: "29AAAAA0000A1Z5",
    storeStatus: "Online",
  },

  users: [
    { _id: 'usr_001', name: 'Kiaan Sharma', email: 'admin@kiaan.com', role: 'Admin', phone: '+91 98765 43210', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80' },
    { _id: 'usr_002', name: 'Aarav Patel', email: 'manager@kiaan.com', role: 'Manager', phone: '+91 98123 45678', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
    { _id: 'usr_003', name: 'Priya Verma', email: 'staff@kiaan.com', role: 'Staff', phone: '+91 98345 67890', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80' },
  ]
};

// Client-side local reactive singleton store
class ClientDataStore {
  constructor() {
    this.data = JSON.parse(JSON.stringify(initialMockData));
  }
}

export const localStore = new ClientDataStore();
